config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :questions
  end

  mathjax 'mathjax'
  root to: "admin/questions#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question, inverse_of: :options
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :sub_topic
  # belongs_to :test
  has_many :options, inverse_of: :question

  

end

app/models/sub_topic.rb
class SubTopic < ApplicationRecord
  has_many :questions
  belongs_to :topic
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :sub_topics
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < AdminController
  before_filter :authenticate_admin!

  def index
    @questions = Question.all
  end

  def create
    params.inspect
    # @option1 = Option.create!()
    # @question = Question.create!(params[:question])
    # Save Images to directory or s3 and populate them on tests.
    question = Question.create!(:description => params[:question][:description],
      :sub_topic => SubTopic.find(params[:question][:sub_topic].to_i))
    correct_option = Option.new(:description => params[:option1], 
      :solution_image => (params[:option1_solution].nil? ? "No Image" : params[:option1_solution].original_filename))
    option2 = Option.new(:description => params[:option2], 
      :solution_image => (params[:option2_solution].nil? ? "No Image" : params[:option2_solution].original_filename))
    option3 = Option.new(:description => params[:option3], 
      :solution_image => (params[:option3_solution].nil? ? "No Image" : params[:option3_solution].original_filename))
    option4 = Option.new(:description => params[:option4], 
      :solution_image => (params[:option4_solution].nil? ? "No Image" : params[:option4_solution].original_filename))
    question.inspect
    correct_option.question = question
    correct_option.save
    option2.question = question
    option2.save
    option3.question = question
    option3.save
    option4.question = question
    option4.save
    question.answer_id = correct_option.id
    question.save
  end

  def new
    @question = Question.new
  end

  def edit

  end

  def show

  end

  def update

  end

  def destroy
    params.inspect
    Question.find(params[:id]).destroy
  end
end

app/controllers/admin_controller.rb
# All end-user controllers should inherit from this controller
class AdminController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/end_user_controller.rb
# All end-user controllers should inherit from this controller
class EndUserController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionController < EndUserController
  
end

app/helpers/admin/question_helper.rb
module Admin::QuestionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/admin/questions/index.html.haml
-@questions = Question.all
%Questions
  =render :partial => "shared/question", :collection => @questions

app/views/admin/questions/new.html.haml
-topics_array = SubTopic.all.map {|s_topic| [s_topic.name, s_topic.id]}
.container.centerBlock
  = form_for @question, :url => {:action => "create"}, :html => {:class => "nifty_form", role: "form"}do |f|
    .form-group
      %h4=f.label "Enter Question Body below:", class: "control-label col-sm-6"
      =f.cktext_area :description, class: "form-control input-lg", :ckeditor => {:toolbar => '', :class => 'mathJax'}
      %h4=f.label "Select Question Topic:", class: "control-label col-sm-3"
      =f.select :sub_topic, options_for_select(topics_array), class: "form-control"
    .form-group
      %h4=f.label "Upload Image if necessary:", class: "control-label col-sm-6"
      =f.file_field :image, class: "form-control input-sm-2"
    .form-group
      %h4=f.label "Enter Correct option:", class: "control-label col-sm-3"
      =cktext_area_tag :option1, "", placeholder: "Enter correct answer", class: 'form-control input-sm-4', :ckeditor => {:toolbar => 'mini'}
      =file_field_tag :option1_solution
    .form-group
      %h4=f.label "Enter all wrong options:", class: "control-label col-sm-6"
      .input-group
        =cktext_area_tag :option2, "", placeholder: "Enter other option", class: 'form-control input-lg', :ckeditor => {:toolbar => 'mini'}
        =file_field_tag :option2_solution
      .input-group
        =cktext_area_tag :option3, "", placeholder: "Enter other option", class: 'form-control input-lg', :ckeditor => {:toolbar => 'mini'}
        =file_field_tag :option3_solution
      .input-group
        =cktext_area_tag :option4, "", placeholder: "Enter other option", class: 'form-control input-lg', :ckeditor => {:toolbar => 'mini'}
        =file_field_tag :option4_solution
    = f.submit 'Create', class: 'btn btn-primary btn-sm-3'

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title TestSeries
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse
      .container-fluid
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "#"} Home
          %li
            %a{:href => "#{root_url}admin/questions"} Questions List
          %li
            %a{:href => "#{root_url}admin/questions/new"} New Question
          %li
            %a{:href => "#"} Contact
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "#"}
              %span.glyphicon.glyphicon-log-in
              Login
      .container-fluid.text-center
        .row.content
          .col-sm-2.sidenav
            %p
              %a{:href => "#"} Link
            %p
              %a{:href => "#"} Link
            %p
              %a{:href => "#"} Link
          .col-sm-8.text-left
            = yield
          .col-sm-2.sidenav
            .well
              %p ADS
            .well
              %p ADS

app/views/shared/_question.html.haml
%table.table
  %tr
    %td
      %p=question.description.html_safe
      %ol.list-group{:type => "A"}
        -question.options.shuffle.each do |option|
          %li=option.description.html_safe
    %td
      =link_to "Delete", "questions/#{question.id}", :method => :delete

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>